# Generated by Django 4.2 on 2023-09-07 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rental", "0004_car_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(default="", upload_to="car_images/"),
        ),
        migrations.AlterField(
            model_name="rental",
            name="rental_date",
            field=models.DateField(default=datetime.date(2023, 9, 7)),
        ),
        migrations.AlterField(
            model_name="rental",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
