# Generated by Django 4.2 on 2023-09-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rental", "0006_audi_bmw_categories_toyota_alter_rental_rental_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audi",
            name="car_image",
        ),
        migrations.RemoveField(
            model_name="bmw",
            name="car_image",
        ),
        migrations.RemoveField(
            model_name="toyota",
            name="car_image",
        ),
        migrations.AddField(
            model_name="audi",
            name="image",
            field=models.ImageField(default="", upload_to="car_images/Audi/"),
        ),
        migrations.AddField(
            model_name="bmw",
            name="image",
            field=models.ImageField(default="", upload_to="car_images/BMW/"),
        ),
        migrations.AddField(
            model_name="toyota",
            name="image",
            field=models.ImageField(default="", upload_to="car_images/Toyota/"),
        ),
    ]
