# Generated by Django 4.2 on 2023-09-14 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rental", "0008_rename_audi_audi_car_rename_bmw_bmw_car_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MERCEDES_CAR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="", upload_to="car_images/Mercedes_benz/"
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("detail", models.CharField(max_length=1000)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name="rental",
            name="rental_date",
            field=models.DateField(default=datetime.date(2023, 9, 14)),
        ),
    ]
