# Generated by Django 4.2 on 2023-09-14 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rental", "0009_mercedes_car_alter_rental_rental_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MERCEDES_CAR",
            new_name="MercedesCar",
        ),
    ]
