# Generated by Django 4.2 on 2023-09-14 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rental", "0010_rename_mercedes_car_mercedescar"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AUDI_CAR",
            new_name="AudiCar",
        ),
        migrations.RenameModel(
            old_name="BMW_CAR",
            new_name="BmwCar",
        ),
        migrations.RenameModel(
            old_name="TOYOTA_CAR",
            new_name="ToyotaCar",
        ),
    ]
