# Generated by Django 4.2 on 2023-09-15 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rental", "0011_rename_audi_car_audicar_rename_bmw_car_bmwcar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audicar",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="bmwcar",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="mercedescar",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="rental",
            name="rental_date",
            field=models.DateField(default=datetime.date(2023, 9, 15)),
        ),
        migrations.AlterField(
            model_name="toyotacar",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
